package celestial.vecmath;

public final class ColorPalette {
	
	public static final Vector3f BLACK = color(0x000000);
 	public static final Vector3f WHITE = color(0xFFFFFF);
 	public static final Vector3f RED = color(0xFF0000);
 	public static final Vector3f LIME = color(0x00FF00);
 	public static final Vector3f BLUE = color(0x0000FF);
 	public static final Vector3f YELLOW = color(0xFFFF00);
 	public static final Vector3f CYAN = color(0x00FFFF);
 	public static final Vector3f MAGENTA = color(0xFF00FF);
 	public static final Vector3f SILVER = color(0xC0C0C0);
 	public static final Vector3f GRAY = color(0x808080);
 	public static final Vector3f MAROON = color(0x800000);
 	public static final Vector3f OLIVE = color(0x808000);
 	public static final Vector3f GREEN = color(0x008000);
 	public static final Vector3f PURPLE = color(0x800080);
 	public static final Vector3f TEAL = color(0x008080);
 	public static final Vector3f NAVY = color(0x000080);
	
 	public static final Vector3f DARK_RED = color(0x8B0000);
 	public static final Vector3f BROWN = color(0xA52A2A);
 	public static final Vector3f FIREBRICK = color(0xB22222);
 	public static final Vector3f CRIMSON = color(0xDC143C);
 	public static final Vector3f TOMATO = color(0xFF6347);
 	public static final Vector3f CORAL = color(0xFF7F50);
 	public static final Vector3f INDIAN_RED = color(0xCD5C5C);
 	public static final Vector3f LIGHT_CORAL = color(0xF08080);
 	public static final Vector3f DARK_SALMON = color(0xE9967A);
 	public static final Vector3f SALMON = color(0xFA8072);
 	public static final Vector3f LIGHT_SALMON = color(0xFFA07A);
 	public static final Vector3f ORANGE_RED = color(0xFF4500);
 	public static final Vector3f DARK_ORANGE = color(0xFF8C00);
 	public static final Vector3f ORANGE = color(0xFFA500);
 	public static final Vector3f GOLD = color(0xFFD700);
 	public static final Vector3f DARK_GOLDENROD = color(0xB8860B);
 	public static final Vector3f GOLDENROD = color(0xDAA520);
 	public static final Vector3f PALE_GOLDENROD = color(0xEEE8AA);
 	public static final Vector3f DARK_KHAKI = color(0xBDB76B);
 	public static final Vector3f KHAKI = color(0xF0E68C);
 	public static final Vector3f YELLOW_GREEN = color(0x9ACD32);
 	public static final Vector3f DARK_OLIVE_GREEN = color(0x556B2F);
 	public static final Vector3f OLIVE_DRAB = color(0x6B8E23);
 	public static final Vector3f LAWN_GREEN = color(0x7CFC00);
 	public static final Vector3f CHART_REUSE = color(0x7FFF00);
 	public static final Vector3f GREEN_YELLOW = color(0xADFF2F);
 	public static final Vector3f DARK_GREEN = color(0x006400);
 	public static final Vector3f FOREST_GREEN = color(0x228B22);
 	public static final Vector3f LIME_GREEN = color(0x32CD32);
 	public static final Vector3f LIGHT_GREEN = color(0x90EE90);
 	public static final Vector3f PALE_GREEN = color(0x98FB98);
 	public static final Vector3f DARK_SEA_GREEN = color(0x8FBC8F);
 	public static final Vector3f MEDIUM_SPRING_GREEN = color(0x00FA9A);
 	public static final Vector3f SPRING_GREEN = color(0x00FF7F);
 	public static final Vector3f SEA_GREEN = color(0x2E8B57);
 	public static final Vector3f MEDIUM_AQUA_MARINE = color(0x66CDAA);
 	public static final Vector3f MEDIUM_SEA_GREEN = color(0x3CB371);
 	public static final Vector3f LIGHT_SEA_GREEN = color(0x20B2AA);
 	public static final Vector3f DARK_SLATE_GRAY = color(0x2F4F4F);
 	public static final Vector3f DARK_CYAN = color(0x008B8B);
 	public static final Vector3f LIGHT_CYAN = color(0xE0FFFF);
 	public static final Vector3f DARK_TURQUOISE = color(0x00CED1);
 	public static final Vector3f TURQUOISE = color(0x40E0D0);
 	public static final Vector3f MEDIUM_TURQUOISE = color(0x48D1CC);
 	public static final Vector3f PALE_TURQUOISE = color(0xAFEEEE);
 	public static final Vector3f AQUA_MARINE = color(0x7FFFD4);
 	public static final Vector3f POWDER_BLUE = color(0xB0E0E6);
 	public static final Vector3f CADET_BLUE = color(0x5F9EA0);
 	public static final Vector3f STEEL_BLUE = color(0x4682B4);
 	public static final Vector3f CORN_FLOWER_BLUE = color(0x6495ED);
 	public static final Vector3f DEEP_SKY_BLUE = color(0x00BFFF);
 	public static final Vector3f DODGER_BLUE = color(0x1E90FF);
 	public static final Vector3f LIGHT_BLUE = color(0xADD8E6);
 	public static final Vector3f SKY_BLUE = color(0x87CEEB);
 	public static final Vector3f LIGHT_SKY_BLUE = color(0x87CEFA);
 	public static final Vector3f MIDNIGHT_BLUE = color(0x191970);
 	public static final Vector3f DARK_BLUE = color(0x00008B);
 	public static final Vector3f MEDIUM_BLUE = color(0x0000CD);
 	public static final Vector3f ROYAL_BLUE = color(0x4169E1);
 	public static final Vector3f BLUE_VIOLET = color(0x8A2BE2);
 	public static final Vector3f INDIGO = color(0x4B0082);
 	public static final Vector3f DARK_SLATE_BLUE = color(0x483D8B);
 	public static final Vector3f SLATE_BLUE = color(0x6A5ACD);
 	public static final Vector3f MEDIUM_SLATE_BLUE = color(0x7B68EE);
 	public static final Vector3f MEDIUM_PURPLE = color(0x9370DB);
 	public static final Vector3f DARK_MAGENTA = color(0x8B008B);
 	public static final Vector3f DARK_VIOLET = color(0x9400D3);
 	public static final Vector3f DARK_ORCHID = color(0x9932CC);
 	public static final Vector3f MEDIUM_ORCHID = color(0xBA55D3);
 	public static final Vector3f THISTLE = color(0xD8BFD8);
 	public static final Vector3f PLUM = color(0xDDA0DD);
 	public static final Vector3f VIOLET = color(0xEE82EE);
 	public static final Vector3f ORCHID = color(0xDA70D6);
 	public static final Vector3f MEDIUM_VIOLET_RED = color(0xC71585);
 	public static final Vector3f PALE_VIOLET_RED = color(0xDB7093);
 	public static final Vector3f DEEP_PINK = color(0xFF1493);
 	public static final Vector3f HOT_PINK = color(0xFF69B4);
 	public static final Vector3f LIGHT_PINK = color(0xFFB6C1);
 	public static final Vector3f PINK = color(0xFFC0CB);
 	public static final Vector3f ANTIQUE_WHITE = color(0xFAEBD7);
 	public static final Vector3f BEIGE = color(0xF5F5DC);
 	public static final Vector3f BISQUE = color(0xFFE4C4);
 	public static final Vector3f BLANCHED_ALMOND = color(0xFFEBCD);
 	public static final Vector3f WHEAT = color(0xF5DEB3);
 	public static final Vector3f CORN_SILK = color(0xFFF8DC);
 	public static final Vector3f LEMON_CHIFFON = color(0xFFFACD);
 	public static final Vector3f LIGHT_GOLDENROD_YELLOW = color(0xFAFAD2);
 	public static final Vector3f LIGHT_YELLOW = color(0xFFFFE0);
 	public static final Vector3f SADDLE_BROWN = color(0x8B4513);
 	public static final Vector3f SIENNA = color(0xA0522D);
 	public static final Vector3f CHOCOLATE = color(0xD2691E);
 	public static final Vector3f PERU = color(0xCD853F);
 	public static final Vector3f SANDY_BROWN = color(0xF4A460);
 	public static final Vector3f BURLY_WOOD = color(0xDEB887);
 	public static final Vector3f TAN = color(0xD2B48C);
 	public static final Vector3f ROSY_BROWN = color(0xBC8F8F);
 	public static final Vector3f MOCCASIN = color(0xFFE4B5);
 	public static final Vector3f NAVAJO_WHITE = color(0xFFDEAD);
 	public static final Vector3f PEACH_PUFF = color(0xFFDAB9);
 	public static final Vector3f MISTY_ROSE = color(0xFFE4E1);
 	public static final Vector3f LAVENDER_BLUSH = color(0xFFF0F5);
 	public static final Vector3f LINEN = color(0xFAF0E6);
 	public static final Vector3f OLD_LACE = color(0xFDF5E6);
 	public static final Vector3f PAPAYA_WHIP = color(0xFFEFD5);
 	public static final Vector3f SEA_SHELL = color(0xFFF5EE);
 	public static final Vector3f MINT_CREAM = color(0xF5FFFA);
 	public static final Vector3f SLATE_GRAY = color(0x708090);
 	public static final Vector3f LIGHT_SLATE_GRAY = color(0x778899);
 	public static final Vector3f LIGHT_STEEL_BLUE = color(0xB0C4DE);
 	public static final Vector3f LAVENDER = color(0xE6E6FA);
 	public static final Vector3f FLORAL_WHITE = color(0xFFFAF0);
 	public static final Vector3f ALICE_BLUE = color(0xF0F8FF);
 	public static final Vector3f GHOST_WHITE = color(0xF8F8FF);
 	public static final Vector3f HONEYDEW = color(0xF0FFF0);
 	public static final Vector3f IVORY = color(0xFFFFF0);
 	public static final Vector3f AZURE = color(0xF0FFFF);
 	public static final Vector3f SNOW = color(0xFFFAFA);
 	public static final Vector3f DIM_GRAY = color(0x696969);
 	public static final Vector3f DARK_GRAY = color(0xA9A9A9);
 	public static final Vector3f LIGHT_GRAY = color(0xD3D3D3);
 	public static final Vector3f GAINSBORO = color(0xDCDCDC);
 	public static final Vector3f WHITE_SMOKE = color(0xF5F5F5);
 	public static final Vector3f SKIN_LIGHT = color(0xFFE0BD);
 	
	public static Vector3f color(int r, int g, int b) {
		return new Vector3f(r / 255f, g / 255f, b / 255f);
	}
	
	public static Vector3f color(int hash) {
		return color((hash >> 16) & 0xFF, (hash >> 8) & 0xFF, hash & 0xFF);
	}
	
}
